### ISSUE TITLE
what is args-exclude1 and args-include1

### ISSUE THREAD

**Issue by kibamin** [phueb/DLSRL#10]
Hi Philip 

how value of f-score is calculate with method **f1-conll05** in **train_tuils.py** ? 
what is **args_exclude1** and **args-include1**  f-score? 

thank you

**Comment by phueb** [comment]
**exclude1** set to True means that the f1-score is calculated without words that were assigned to the label "1" (these are words that do not have argument labels in the data). Setting it to False is a more rigorous evaluation than setting it to True, because it requires the model to identify non-arguments correctly (in addition to identifying the labels for arguments correctly).

**Comment by kibamin** [comment]
> **exclude1** set to True means that the f1-score is calculated without words that were assigned to the label "1" (these are words that do not have argument labels in the data). Setting it to False is a more rigorous evaluation than setting it to True, because it requires the model to identify non-arguments correctly (in addition to identifying the labels for arguments correctly).

thanks Philip 👍

**Comment by phueb** [comment]
The model is now evaluated with the official perl evaluation script provided by the conll05 shared task
